import type { Metadata } from 'next';
import Link from 'next/link';
import { cookies } from 'next/headers';

export const dynamic = 'force-dynamic';

export const metadata: Metadata = {
  title: 'Best Time to Post on YouTube — Data-Driven Tool | YTubViral',
  description:
    'Descubre la mejor hora para publicar en YouTube con datos reales de tu canal. Heatmap, mejores franjas horarias y consejos de IA.',
  alternates: { canonical: 'https://ytubviral.com/features/best-time' },
  openGraph: {
    title: 'Best Time to Post on YouTube | YTubViral',
    description: 'Find your optimal publishing schedule based on real channel data. Free heatmap and AI tips.',
    url: 'https://ytubviral.com/features/best-time',
    type: 'website',
  },
};

const FAQ_ES = [
  { q: '¿Cómo calcula la mejor hora?', a: 'Analizamos el historial de rendimiento de tus vídeos: cuándo obtuvieron más vistas, engagement y suscriptores en las primeras horas. No es un dato genérico — es personalizado para TU canal.' },
  { q: '¿Necesito conectar mi canal de YouTube?', a: 'Sí. Necesitas conectar tu cuenta de YouTube (Google OAuth) para que podamos acceder a tus datos de analytics. Solo leemos datos — nunca publicamos ni modificamos nada.' },
  { q: '¿Funciona para canales pequeños?', a: 'Necesitas al menos 10-15 vídeos publicados para que el análisis sea fiable. Con menos vídeos los datos son insuficientes para detectar patrones.' },
  { q: '¿Qué es el heatmap?', a: 'Un mapa de calor que muestra los 7 días de la semana × 24 horas. Las celdas más rojas indican los momentos con mayor rendimiento histórico. Los 3 mejores slots aparecen destacados.' },
  { q: '¿Los tips de IA son genéricos?', a: 'No. Se generan analizando los patrones específicos de tu canal: si tu audiencia es más activa entre semana, si los fines de semana funcionan mejor, etc.' },
];

const FAQ_EN = [
  { q: 'How does it calculate the best time?', a: 'We analyze your video performance history: when they got the most views, engagement, and subscribers in the first hours. Not generic data — personalized for YOUR channel.' },
  { q: 'Do I need to connect my YouTube channel?', a: 'Yes. You need to connect your YouTube account (Google OAuth) so we can access your analytics data. We only read data — never post or modify anything.' },
  { q: 'Does it work for small channels?', a: 'You need at least 10-15 published videos for reliable analysis. With fewer videos there\'s not enough data to detect patterns.' },
  { q: 'What is the heatmap?', a: 'A heat map showing 7 days × 24 hours. Redder cells indicate times with the best historical performance. The top 3 slots are highlighted.' },
  { q: 'Are the AI tips generic?', a: 'No. They\'re generated by analyzing your channel\'s specific patterns: whether your audience is more active on weekdays, if weekends perform better, etc.' },
];

export default async function BestTimeFeature() {
  const cookieStore = await cookies();
  const lang = cookieStore.get('ytubviral_lang')?.value === 'en' ? 'en' : 'es';
  const t = (es: string, en: string) => lang === 'en' ? en : es;
  const FAQ = lang === 'en' ? FAQ_EN : FAQ_ES;

  const features = [
    { title: t('Heatmap 7×24', '7×24 Heatmap'), desc: t('Mapa de calor visual con los 7 días de la semana y las 24 horas del día. Identifica patrones de un vistazo.', 'Visual heat map with 7 days and 24 hours. Identify patterns at a glance.') },
    { title: t('Top 3 slots', 'Top 3 Slots'), desc: t('Los 3 mejores momentos para publicar, ordenados por rendimiento. Con medallas de oro, plata y bronce.', 'The 3 best moments to publish, ranked by performance. With gold, silver, and bronze medals.') },
    { title: t('Tips de IA personalizados', 'Personalized AI Tips'), desc: t('Recomendaciones generadas por IA basadas en los patrones específicos de tu canal y audiencia.', 'AI-generated recommendations based on your channel\'s specific patterns and audience.') },
    { title: t('Basado en datos reales', 'Based on Real Data'), desc: t('No usamos promedios genéricos. Cada recomendación se calcula con los datos de rendimiento de tus propios vídeos.', 'We don\'t use generic averages. Every recommendation is calculated from your own video performance data.') },
  ];

  const steps = [
    { step: '1', title: t('Conecta tu canal', 'Connect your channel'), desc: t('Inicia sesión con Google y autoriza el acceso de lectura a YouTube Analytics.', 'Sign in with Google and authorize read access to YouTube Analytics.') },
    { step: '2', title: t('Analizamos tu historial', 'We analyze your history'), desc: t('Procesamos el rendimiento de tus vídeos publicados: vistas en las primeras horas, engagement y crecimiento de suscriptores.', 'We process your published video performance: views in the first hours, engagement, and subscriber growth.') },
    { step: '3', title: t('Recibe tu horario óptimo', 'Get your optimal schedule'), desc: t('Heatmap visual + top 3 slots + tip de IA. Actualizable en cualquier momento cuando publiques más vídeos.', 'Visual heatmap + top 3 slots + AI tip. Refreshable anytime as you publish more videos.') },
  ];

  const audiences = [
    { title: t('Creadores consistentes', 'Consistent creators'), desc: t('Publicas al menos 1 vídeo por semana y quieres maximizar el impacto de cada publicación eligiendo el mejor momento.', 'You publish at least 1 video per week and want to maximize each upload\'s impact by choosing the best time.') },
    { title: t('Canales en crecimiento', 'Growing channels'), desc: t('Estás en la fase de 1K-100K subs donde cada vídeo cuenta. Publicar a la hora correcta puede ser la diferencia entre 5K y 50K vistas.', 'You\'re in the 1K-100K subs phase where every video counts. Posting at the right time can be the difference between 5K and 50K views.') },
    { title: t('Equipos de contenido', 'Content teams'), desc: t('Gestionas varios canales y necesitas datos objetivos para programar publicaciones, no intuiciones.', 'You manage multiple channels and need objective data to schedule uploads, not guesswork.') },
  ];

  return (
    <div className="min-h-screen" style={{ background: 'var(--ink)' }}>
      <section className="max-w-5xl mx-auto px-6 pt-24 pb-16 text-center">
        <p className="font-mono-jb text-[13px] tracking-[0.2em] uppercase mb-4" style={{ color: '#FFE800' }}>
          {t('MEJOR HORA PARA PUBLICAR', 'BEST TIME TO POST')}
        </p>
        <h1 className="font-display font-bold text-4xl md:text-6xl leading-tight mb-6">
          {t('Publica a la hora perfecta', 'Post at the Perfect Time')}<br />
          <span style={{ color: 'var(--red)' }}>{t('según los datos de tu canal', 'based on your channel data')}</span>
        </h1>
        <p className="text-lg md:text-xl text-zinc-400 max-w-2xl mx-auto mb-8">
          {t('Deja de adivinar cuándo publicar. Analizamos el rendimiento real de tus vídeos para encontrar tu horario óptimo.',
            'Stop guessing when to publish. We analyze your real video performance to find your optimal schedule.')}
        </p>
        <div className="flex flex-wrap justify-center gap-4">
          <Link href="/signup" className="btn-offset px-8 py-3 text-[15px] font-display">
            {t('Analizar mi canal — gratis', 'Analyze my channel — free')}
          </Link>
          <Link href="/best-time" className="btn-offset btn-offset-white px-8 py-3 text-[15px] font-display">
            {t('Ver mi heatmap', 'See my heatmap')}
          </Link>
        </div>
      </section>

      <section className="max-w-5xl mx-auto px-6 py-16">
        <h2 className="font-display font-bold text-2xl md:text-3xl mb-10 text-center">
          {t('Qué obtienes', 'What you get')}
        </h2>
        <div className="grid md:grid-cols-2 gap-6">
          {features.map((f) => (
            <div key={f.title} className="soft-card p-5">
              <h3 className="font-display font-bold text-base mb-2">{f.title}</h3>
              <p className="text-zinc-400 text-sm leading-relaxed">{f.desc}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="max-w-4xl mx-auto px-6 py-16">
        <h2 className="font-display font-bold text-2xl md:text-3xl mb-10 text-center">
          {t('Cómo funciona', 'How it works')}
        </h2>
        <div className="space-y-8">
          {steps.map((s) => (
            <div key={s.step} className="flex gap-5 items-start">
              <div className="flex-shrink-0 w-10 h-10 rounded-full flex items-center justify-center font-display font-bold text-lg" style={{ background: 'var(--red)', color: 'white' }}>{s.step}</div>
              <div>
                <h3 className="font-display font-bold text-lg mb-1">{s.title}</h3>
                <p className="text-zinc-400 text-sm leading-relaxed">{s.desc}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      <section className="max-w-5xl mx-auto px-6 py-16">
        <h2 className="font-display font-bold text-2xl md:text-3xl mb-8 text-center">
          {t('¿Para quién es?', 'Who is this for?')}
        </h2>
        <div className="grid md:grid-cols-3 gap-6">
          {audiences.map((u) => (
            <div key={u.title} className="soft-card p-5">
              <h3 className="font-display font-bold text-base mb-2">{u.title}</h3>
              <p className="text-zinc-400 text-sm leading-relaxed">{u.desc}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="max-w-3xl mx-auto px-6 py-16">
        <h2 className="font-display font-bold text-2xl md:text-3xl mb-8 text-center">
          {t('Preguntas frecuentes', 'Frequently asked questions')}
        </h2>
        <div className="space-y-6">
          {FAQ.map((item) => (
            <div key={item.q} className="soft-card p-5">
              <h3 className="font-display font-bold text-base mb-2">{item.q}</h3>
              <p className="text-zinc-400 text-sm leading-relaxed">{item.a}</p>
            </div>
          ))}
        </div>
      </section>

      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: FAQ_ES.map((item) => ({ '@type': 'Question', name: item.q, acceptedAnswer: { '@type': 'Answer', text: item.a } })) }) }} />

      <section className="max-w-3xl mx-auto px-6 py-20 text-center">
        <h2 className="font-display font-bold text-2xl md:text-3xl mb-4">
          {t('¿Listo para publicar en el momento perfecto?', 'Ready to publish at the perfect moment?')}
        </h2>
        <p className="text-zinc-400 mb-8">{t('Gratis para siempre. Sin tarjeta. Empieza en 10 segundos.', 'Free forever. No credit card. Start in 10 seconds.')}</p>
        <Link href="/signup" className="btn-offset px-10 py-4 text-[15px] font-display">
          {t('Descubrir mi mejor hora — gratis', 'Find my best time — free')}
        </Link>
      </section>
    </div>
  );
}
