'use client';

import { useState, useEffect } from 'react';

export default function LegalPage() {
  const [lang, setLang] = useState<'es'|'en'>('es');
  useEffect(() => {
    const s = localStorage.getItem('ytubviral_lang') as 'es'|'en' | null;
    if (s) setLang(s);
  }, []);
  const t = (es: string, en: string) => lang === 'en' ? en : es;

  return (
    <div className="min-h-screen grain" style={{ background: 'var(--ink)', color: 'var(--text)' }}>
      <div className="max-w-3xl mx-auto px-6 py-16 space-y-10">

        <div>
          <a href="/" className="inline-flex items-center gap-2 mb-10">
            <svg width="24" height="24" viewBox="0 0 32 32" fill="none">
              <circle cx="16" cy="16" r="13" stroke="#9B2020" strokeWidth="2.2"/>
              <polygon points="13,10.5 13,21.5 23,16" fill="#9B2020"/>
            </svg>
            <span className="font-display font-bold text-[14px] text-white">YTubViral<span style={{ color: 'var(--red)' }}>.</span>com</span>
          </a>
          <p className="font-mono-jb text-[10px] tracking-[0.3em] uppercase mb-3" style={{ color: 'var(--red)' }}>LEGAL</p>
          <h1 className="font-display font-bold text-4xl text-white">{t('Aviso Legal', 'Legal Notice')}</h1>
          <p className="text-zinc-500 text-sm mt-2 font-mono-jb">{t('Última actualización: abril de 2026', 'Last updated: April 2026')}</p>
        </div>

        {[
          {
            title: t('Titular del sitio web', 'Website owner'),
            body: t(
              'El presente sitio web ytubviral.com y el servicio YTubViral son gestionados por un particular con domicilio en España. Email de contacto: ytbeviral@gmail.com',
              'This website ytubviral.com and the YTubViral service are managed by an individual based in Spain. Contact email: ytbeviral@gmail.com'
            ),
          },
          {
            title: t('Objeto', 'Purpose'),
            body: t(
              'YTubViral es un servicio de generación de contenido asistido por inteligencia artificial dirigido a creadores de contenido en YouTube. El servicio se presta a través de Internet y está disponible globalmente.',
              'YTubViral is an AI-assisted content generation service aimed at YouTube content creators. The service is provided over the Internet and is available globally.'
            ),
          },
          {
            title: t('Propiedad intelectual', 'Intellectual property'),
            body: t(
              'El diseño, código fuente, logotipos y demás elementos del sitio web son propiedad de YTubViral o de sus respectivos titulares. Queda prohibida su reproducción total o parcial sin autorización expresa. El contenido generado por los usuarios a través del servicio es propiedad de dichos usuarios, sin que YTubViral reclame derechos sobre el mismo.',
              'The design, source code, logos and other elements of the website are the property of YTubViral or their respective owners. Reproduction in whole or in part without express authorisation is prohibited. Content generated by users through the service is owned by those users; YTubViral claims no rights over it.'
            ),
          },
          {
            title: t('Exclusión de responsabilidad', 'Disclaimer'),
            body: t(
              'YTubViral no garantiza la exactitud, completitud ni idoneidad del contenido generado por los modelos de inteligencia artificial. El usuario es el único responsable del uso que haga de dicho contenido. YTubViral no se responsabiliza de posibles daños derivados del uso del servicio, interrupciones técnicas, pérdida de datos o cualquier otro perjuicio directo o indirecto.',
              'YTubViral does not guarantee the accuracy, completeness or suitability of content generated by AI models. The user is solely responsible for the use of such content. YTubViral is not liable for any damages arising from use of the service, technical interruptions, data loss or any other direct or indirect harm.'
            ),
          },
          {
            title: t('Legislación aplicable', 'Applicable law'),
            body: t(
              'El presente aviso legal se rige por la legislación española, en particular por la Ley 34/2002 (LSSI-CE), el Reglamento (UE) 2016/679 (RGPD), la Ley Orgánica 3/2018 (LOPDGDD) y el Real Decreto Legislativo 1/2007 de defensa de los consumidores.',
              'This legal notice is governed by Spanish law, in particular Law 34/2002 (LSSI-CE), Regulation (EU) 2016/679 (GDPR), Organic Law 3/2018 (LOPDGDD) and Royal Legislative Decree 1/2007 on consumer protection.'
            ),
          },
          {
            title: t('Resolución de litigios en línea', 'Online dispute resolution'),
            body: t(
              'Conforme al Reglamento (UE) 524/2013, los usuarios residentes en la UE pueden acceder a la plataforma de resolución de litigios en línea de la Comisión Europea en: ec.europa.eu/consumers/odr',
              'Pursuant to Regulation (EU) 524/2013, users resident in the EU may access the European Commission\'s online dispute resolution platform at: ec.europa.eu/consumers/odr'
            ),
          },
          {
            title: t('Contacto', 'Contact'),
            body: t('Para cualquier consulta legal: ytbeviral@gmail.com', 'For any legal enquiries: ytbeviral@gmail.com'),
          },
        ].map((s, i) => (
          <section key={i} className="space-y-3 pb-8 border-b border-white/5 last:border-0">
            <h2 className="font-display font-bold text-lg text-white">{s.title}</h2>
            <p className="text-zinc-400 text-sm leading-relaxed">{s.body}</p>
          </section>
        ))}

        <div className="flex gap-5 font-mono-jb text-xs text-zinc-600 pt-4">
          <a href="/terms" className="hover:text-zinc-400 transition">{t('Términos', 'Terms')}</a>
          <a href="/privacy" className="hover:text-zinc-400 transition">{t('Privacidad', 'Privacy')}</a>
          <a href="/" className="hover:text-zinc-400 transition">{t('Volver al inicio', 'Back to home')}</a>
        </div>
      </div>
    </div>
  );
}
