import { NextResponse } from 'next/server';
import { generateSocialPost } from '@/lib/agent/content-generator';
import { publishToInstagram, retryPendingFacebookPost } from '@/lib/agent/meta-agent';
import { getOrCreateDailyBrandImage } from '@/lib/agent/ideogram-image';
import { buildInfographicUrl } from '@/lib/agent/infographic-generator';
import { sendNotificationEmail } from '@/lib/agent/gmail-agent';
import { runYoutubeAgent } from '@/lib/agent/youtube-agent';
import { runFeedbackAgent } from '@/lib/agent/feedback-agent';
import { processAbTests } from '@/lib/ab-test-processor';
import { prisma } from '@/lib/prisma';

export const maxDuration = 60;

function verifyCronSecret(request: Request): boolean {
  const secret = process.env.CRON_SECRET;
  if (!secret) return false;
  return request.headers.get('authorization') === `Bearer ${secret}`;
}

export async function GET(request: Request) {
  if (!verifyCronSecret(request)) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const errors: string[] = [];
  const results: Record<string, unknown> = {};

  try {
    // 1. Generate Instagram content + run agents in parallel (evening = Instagram only)
    // Gmail agent disabled here — YCML (local PM2 agent) handles inbox every 30min
    const [instagram, youtubeResult] =
      await Promise.allSettled([
        generateSocialPost('instagram', 'evening'),
        runYoutubeAgent(),
      ]);

    const ig = instagram.status === 'fulfilled' ? instagram.value : null;

    if (instagram.status === 'rejected') errors.push(`Instagram content: ${instagram.reason}`);

    // Facebook retry — reactivado 2026-05-16
    const fbRetry = await retryPendingFacebookPost().catch(err => ({
      success: false as const, skipped: false,
      error: err instanceof Error ? err.message : String(err),
    }));
    results.facebookRetry = fbRetry;

    // 0. Send feedback emails to users registered 3 days ago
    const feedbackResult = await runFeedbackAgent().catch(err => ({
      sent: 0,
      errors: [`Feedback agent: ${err instanceof Error ? err.message : err}`],
    }));
    errors.push(...feedbackResult.errors);
    results.feedback = { sent: feedbackResult.sent };

    // YouTube agent results
    const youtube = youtubeResult.status === 'fulfilled'
      ? youtubeResult.value
      : { processed: 0, replied: 0, errors: [`YouTube agent failed: ${youtubeResult.reason}`] };
    errors.push(...youtube.errors);
    results.youtube = { processed: youtube.processed, replied: youtube.replied };

    // 2. Publish Instagram with AI image (evening slot — 18:30 Madrid).
    //    Reuses the day's shared brand image (generated by the morning cron);
    //    only generates if none exists yet. Satori fallback if Ideogram fails.
    if (ig) {
      const igImageUrl = (await getOrCreateDailyBrandImage(ig)) ?? buildInfographicUrl(ig);
      const igResult = await publishToInstagram(ig, igImageUrl);
      results.instagram = igResult;
      // skipped = ya se publicó hoy (dedup normal, no un error). El post de IG lo
      // hace el cron matutino; por la tarde este dedup saltaba a diario y mandaba
      // un "[YTubViral Agent] Errores en cron vespertino" falso (silenciado 03/09).
      if (!igResult.success && !igResult.skipped) errors.push(`Instagram: ${igResult.error}`);
    }

    // Process A/B tests (switch variants, complete tests)
    const abResult = await processAbTests().catch(err => ({
      switched: 0,
      completed: 0,
      errors: [`A/B test processor: ${err instanceof Error ? err.message : String(err)}`],
    }));
    results.abTests = { switched: abResult.switched, completed: abResult.completed };
    errors.push(...abResult.errors);

    if (errors.length > 0) {
      await sendNotificationEmail(
        '[YTubViral Agent] Errores en cron vespertino',
        errors.join('\n')
      ).catch(() => {});
    }

    return NextResponse.json({ ok: true, results, errors });
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error('[cron/evening]', msg);
    return NextResponse.json({ ok: false, error: msg }, { status: 500 });
  }
}
